version: "3.3"

services:

  coredns:
    image: "coredns/coredns:1.9.3"
    restart: "unless-stopped"
    command: "-conf /root/Corefile"
    ports:
      - "53:53/udp"
    volumes:
      - "/mnt/d/docker/coredns/root:/root"
    labels:
      - "traefik.enable=false"
    network_mode: bridge


  hub-agent:
    image: ghcr.io/traefik/hub-agent-traefik:v0.7.0
    env_file:
      - hub-agent.env
    restart: "on-failure"
    command:
      - run
      - --hub.token=${TRAEFIK_HUB_TOKEN}
      - --auth-server.advertise-url=http://hub-agent
      - --traefik.host=traefik
      - --traefik.tls.insecure=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - devtools-traefik


  traefik:
    image: "traefik:v2.7"
    restart: "unless-stopped"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - '--providers.docker.defaultRule=Host(`{{if index .Labels "com.docker.compose.service" }}{{ index .Labels "com.docker.compose.service" }}.leveraging.com{{else}}{{ trimPrefix `/` .Name }}.leveraging.com{{end}}`)'
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/config/"
      - "--providers.file.watch=true"
      - "--experimental.hub=true"
      - "--hub.tls.insecure=true"
      - "--metrics.prometheus.addrouterslabels=true"
#      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/mnt/d/docker/traefik/config:/config"
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.leveraging.com`)"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.services.api.loadbalancer.server.port=8080"


  httpbin:
    image: "kennethreitz/httpbin:latest"
    restart: "unless-stopped"
    labels:
      - "traefik.http.routers.httpbin.rule=Host(`httpbin.leveraging.com`)"
      - "traefik.http.routers.httpbin.tls=true"
      - "traefik.http.services.httpbin-devtools.loadbalancer.server.port=80"


  dwplay:
    image: "dnr/dwplay:2.5.0-SNAPSHOT"
    #image: "machaval/dw-playground:2.3.1-SNAPSHOT"
    restart: "unless-stopped"
    labels:
      - "traefik.http.routers.dwplay.rule=Host(`dwplay.leveraging.com`)"
      - "traefik.http.routers.dwplay.tls=true"
      - "traefik.http.services.dwplay-devtools.loadbalancer.server.port=8081"

networks:
  proxy:
    external: true

